### ISSUE TITLE
Hidden devices return

### ISSUE THREAD

**Issue by richsimpson** [Moustachauve/WLED-Native-iOS#6] opened 2023-06-06 08:22 UTC
Hi. Great app. I found the original WLED app didn’t display or work right on iPhone pro. 

On this app all seems great other than devices I hide come back after some time. After the app is force closed. 

Any idea if it’s fixable or just one of those things? 

My use case is 3 strips that are all essentially controlled as 1. So wled 1 is called summer house. Wled 2 and 3 are hidden and just sync from wled 1.

**Comment by Moustachauve** [comment] 2023-09-24 04:58
This is a duplicate of #4.

**Closed by Moustachauve** 2023-09-24 04:58 UTC
